/**
 * Represents a product entity used throughout the frontend.
 * 
 * This class mirrors de Product class from the backend.
 * The data is retrieved from and persisted to a MySQL DB via the backend.
 */
export class Product {
    /** Unique identifier of the product (autogenerated when a product is created). */
    id_product !: number;

    /** Brief description of the product. */
    description !: string;

    /** 
     * Price of the product.
     * Must be a positive number.
     * Validated both on the frontend (add-product form) and backend (jakarta validation).
     */
    price !: number;

    /**
     * Quantity of the product in stock.
     * Must be a non-negative integer.
     * Validated both on the frontend (add-product form) and backend (jakarta validation).
     */
    stock !: number;
}
